language: python

python: 
        - "3.6.8"
os: linux

services: mysql

before_install:
        - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('admin12345') where User='dbadmin'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo mysql_upgrade
        - sudo service mysql restart
        - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS ecommerce_test;'

# command to install dependencies
install:
        - pip install -r requirements.txt 
#command to run tests
script:
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test ecommerce        
