language: python

python: 
        - "3.6.8"
os: linux

sudo: true

services: mysql

before_install:
        - sudo mysql -u root --password="root" < test/travis.sql
# command to install dependencies
install:
        - pip install -r requirements.txt 
#command to run tests
script:
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py test ecommerce        
