language: python
python:
  - "2.7.4"
  - "3.4"
env:
  -DJANGO=1.8 DB=sqlite3

 # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
 # command to run tests
script:
  - pytest
  - coverage run -- mysource=myapp_1, myapp_2 manage.py test
after_success:
  coveralls
