language: python
# python versions
python:
  - "3.4"
  - "2.7.4"
env:
  -DJANGO=1.8 DB=sqlite3
# install requirements
install:
  - pip install -r
requirements.txt
  - pip install coveralls
# To run tests
script:
  - coverage run --
source=my_app1, my_app2
manage.py test
#Send coverage report to coveralls
after_success:
  coveralls
