language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
env:
  -DJANGO=1.8 DB=sqlite3

 # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
 # command to run tests
script:
  - pytest
  - coverage run -- mysource=myapp_1, myapp_2 manage.py test
after_success:
  coveralls
